dist: trusty
sudo: required

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.9.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

jobs:
  include:
    - &build-mraa-base-image
      stage: Build mraa-base image
      env: TARGET=mraa-base
      script: docker-compose build ${TARGET}
      before_deploy: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
      deploy:
        - provider: script
          script: docker push ${DOCKER_USERNAME}/${TARGET}
    - &build-mraa-image
      <<: *build-mraa-base-image
      stage: Build mraa images
      env: TARGET=mraa-python
    - <<: *build-mraa-image
      env: TARGET=mraa-java
    - <<: *build-mraa-image
      env: TARGET=mraa-android
    - <<: *build-mraa-image
      env: TARGET=mraa-node4
    - <<: *build-mraa-image
      env: TARGET=mraa-node5
    - <<: *build-mraa-image
      env: TARGET=mraa-node6
    - <<: *build-mraa-image
      env: TARGET=mraa-all
    - &build-upm-base-image
      <<: *build-mraa-base-image
      stage: Build upm-base image
      env: TARGET=upm-base
    - &build-upm-image
      <<: *build-upm-base-image
      stage: Build upm images
      env: TARGET=mraa-python
    - <<: *build-upm-image
      env: TARGET=upm-python
    - <<: *build-upm-image
      env: TARGET=upm-java
    - <<: *build-upm-image
      env: TARGET=upm-android
    - <<: *build-upm-image
      env: TARGET=upm-node4
    - <<: *build-upm-image
      env: TARGET=upm-node5
    - <<: *build-upm-image
      env: TARGET=upm-node6
    - <<: *build-upm-image
      env: TARGET=upm-all
